<body>
    <header class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-expand-md navbar-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#"><img src="assets/images/favicon.ico" alt="Icon for SkillSwap" class="justify-center allign-left"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="index.php">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="skills.php">All Skills</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="gallery.php">Gallery</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="add.php">Add Skill</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <form class="d-flex justify-content-end">
                                    <button class="sBarB btn btn-light" type="submit">
                                        <span class="material-icons">search</span>
                                    </button>
                                    <input class="sBarT form-control me-2" type="text" placeholder="Search Skills...">
                                </form>
                            </li>
                        </ul>
                        
                    </div>
                    
                </div>
            </nav>
        </div>
    </header>
